jenkins:
  systemMessage: "Pipeline CI/CD Otomatis untuk Mini Project 3 Kelompok 1"
  numExecutors: 2
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "adminpassword"

# PINDAHKAN KE SINI (Rata Kiri/Root Level)
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "dockerhub-credentials"
              username: "abhi1020"
              password: "${DOCKER_HUB_PASSWORD}" # Diambil dari ENV kontainer
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: "target-vm-ssh"
              username: "azureuser"
              privateKeySource:
                directEntry:
                  privateKey: "${TARGET_VM_PRIVATE_KEY}"

jobs:
  - script: >
      pipelineJob('CI-CD-Pipeline-App') {
        definition {
          cpsScm {
            scm {
              git {
                remote { url('https://github.com/ludw1gd/devops-miniproject-3-kel1.git') }
                branches('main')
              }
            }
            scriptPath('jenkins/Jenkinsfile')
          }
        }
      }