jenkins:
  systemMessage: "Pipeline CI/CD Otomatis untuk Mini Project 3 Kelompok 1"
  numExecutors: 2
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "adminpassword" # Segera ganti setelah login pertama

  # Otomatisasi Kredensial
  credentials:
    system:
      domainCredentials:
        - credentials:
            - usernamePassword:
                scope: GLOBAL
                id: "dockerhub-credentials"
                username: "abhi1020" # Username Docker Hub Anda
                password: "${DOCKER_HUB_PASSWORD}"
            - basicSSHUserPrivateKey:
                scope: GLOBAL
                id: "target-vm-ssh"
                username: "azureuser"
                privateKeySource:
                  directEntry:
                    privateKey: "${TARGET_VM_PRIVATE_KEY}"

unclassified:
  location:
    url: "http://85.211.243.25:8080/"

# Otomatisasi Pembuatan Job Pipeline 
jobs:
  - script: >
      pipelineJob('CI-CD-Pipeline-App') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/ludw1gd/devops-miniproject-3-kel1.git')
                }
                branches('main')
              }
            }
            scriptPath('jenkins/Jenkinsfile') # Jalankan Jenkinsfile dari folder /jenkins
          }
        }
      }