---
- name: Persiapan Node (Install Docker)
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Install dependencies dasar
      apt:
        name: [apt-transport-https, ca-certificates, curl, software-properties-common, gnupg]
        state: present

    - name: Tambahkan GPG key Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Tambahkan repository Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Install Docker Engine
      apt:
        name: [docker-ce, docker-ce-cli, containerd.io, docker-compose-plugin]
        state: present

- name: Konfigurasi Jenkins via JCasC
  hosts: jenkins
  become: yes
  tasks:
    - name: Buat direktori untuk JCasC
      file:
        path: /var/jenkins_home/casc_configs
        state: directory
        owner: "1000"
        group: "1000"
        mode: '0755'

    - name: Copy file konfigurasi JCasC
      copy:
        src: ./jenkins.yaml
        dest: /var/jenkins_home/casc_configs/jenkins.yaml
        owner: "1000"
        group: "1000"

    - name: Hapus kontainer lama jika ada
      command: docker rm -f jenkins
      ignore_errors: yes

    - name: Set permission folder Jenkins Home untuk UID 1000
      file:
        path: /var/jenkins_home
        state: directory
        owner: "1000"
        group: "1000"
        mode: '0755'

    - name: Jalankan Jenkins Container
      docker_container:
        name: jenkins
        image: jenkins/jenkins:lts
        state: started
        ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/jenkins_home:/var/jenkins_home